version: '2.1'
services:
  kafka:
    image: confluent/kafka
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper
    depends_on:
      - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
        - "2181:2181"
